# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  kennisbank:
    output:   true
  posts:
    output:   true
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Handling Reading
safe:                 true
include:              ["_pages"]
exclude:              ["/vendor/", "Gemfile", "Gemfile.lock"]
keep_files:           [".git", ".gitignore",".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter:  false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: ["jekyll-sitemap", "jekyll-feed","jemoji"]
gems:      ["jekyll-sitemap", "jekyll-feed","jemoji"]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
baseurl: "" # Set this value to "" if you want your site to be root
show_dir_listing: false

# Outputting
permalink:     /:title/
paginate_path: /page:num
timezone: Europe/Amsterdam # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

quiet:    false
verbose:  false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  enable_coderay: false

liquid:
  error_mode: warn

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Site settings
title: Online Gebeuren
subtitle: "A free HTML5 agency template"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # _kennisbank
  - scope:
      path: ""
      type: kennisbank
    values:
      layout: kennisbank
      permalink: /:collection/:path/
